# Codecov configuration to make it a bit less noisy
coverage:
  status:
    patch: false
    project:
      default:
        threshold: 50%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
ignore:
  - "menger_curvature/_version.py"
# Add env section for coverage runs
env:
  global:
    - NUMBA_DISABLE_JIT=1  # Disable JIT only during coverage testing